FROM ghcr.io/graalvm/native-image:ol8-java17-22 AS builder

RUN microdnf install -y findutils

COPY . .

RUN ./gradlew nativeCompile -Pnative

FROM ubuntu:lunar-20230128 as runtime

COPY --from=builder /app/build/native/nativeCompile/rtd-ms-alternative-gateway .

ENTRYPOINT ["./rtd-ms-alternative-gateway"]